dist: trusty
language: cpp

matrix:
  include:
  - os: linux
    language: cpp
    compiler: gcc
    env: COMPILER="g++-5"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-5
        - build-essential
        - cmake
  - os: linux
    language: cpp
    compiler: clang
    env: COMPILER="clang++"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - build-essential
        - cmake
  - os: osx
    language: cpp
    compiler: clang

script:
- mkdir build
- cd build
- cmake -DCMAKE_CXX_COMPILER=$COMPILER ..
- make
- ctest --output-on-failure
- ../bin/leibniz
